from ..endpoints import login
from ..endpoints import crud_user
from ..endpoints import crud_section
from ..endpoints import crud_standard
from ..endpoints import crud_class
from ..endpoints import crud_attendance
from ..endpoints import crud_mark
from ..endpoints import crud_branch
from ..endpoints import crud_academic_data
from ..endpoints import crud_subject
from ..endpoints import crud_term
from ..endpoints import crud_time_table
from ..endpoints import crud_exam
from ..endpoints import crud_scholorship
from ..endpoints import crud_student_scholorship
from ..endpoints import crud_classroom
from ..endpoints import crud_class_timetable
from ..endpoints import crud_class_subject
from ..endpoints import crud_exam_standard
from ..endpoints import crud_fees
from ..endpoints import password_reset
from ..endpoints import crud_leave_request