from .login import Login
from .crud_user import *
from .reset_password import ResetPassword
from .request_otp import RequestOtp
from .crud_section import *
from .crud_standard import *
from .crud_class import *
from .crud_attendance import *
from .crud_mark import *
from .crud_branch import *
from .crud_academic_data import *
from .crud_subject import *
from .crud_term import *
from .crud_time_table import *
from .crud_exam import *
from .crud_scholorship import *
from .crud_student_scholorship import *
from .crud_classroom import *
from .crud_class_subject import *
from .crud_class_timetable import *
from .crud_exam_standard import *
from .crud_fees import *
from .crud_leave_request import *